In [2]:
import numpy as np

print(np.__version__)


1.26.3


In [3]:

null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Create a NumPy array
arr = np.zeros((10, 10))  # For example, a 10x10 array of zeros

# Get the memory size of the array
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 800 bytes


In [5]:
# Create a null vector of size 10
null_vector = np.zeros(10)

# Set the fifth value (index 4) to 1
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
vector = np.arange(10, 50)

reverse_vector = vector[ : : -1]

print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
array = np.arange(9)

matrix = array.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
elements = [1, 2, 0, 0, 4, 0]

print(elements[1])
print(elements[4])

2
4


In [ ]:
array = np.zeros(9)


matrix =array.reshape(3, 3)
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array = np.random.rand(3, 3, 3)

print(array)

[[[0.83454717 0.53916213 0.79792188]
  [0.17606182 0.44712081 0.27883898]
  [0.14452731 0.12224068 0.96876143]]

 [[0.9365376  0.18977954 0.00958507]
  [0.59519795 0.79298689 0.60350539]
  [0.88530906 0.56145482 0.2796684 ]]

 [[0.11861303 0.05881352 0.84642937]
  [0.29279586 0.88679434 0.9951465 ]
  [0.91205418 0.3630624  0.59272527]]]


In [ ]:
array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.021091560140804266
Maximum value: 0.9989795409398605


In [ ]:
random_vector = np.random.rand(30)

min_value = np.min(random_vector)
max_value = np.max(random_vector)
print("the minimun value: ", min_value, "and maximum value: ", max_value)

NameError: name 'np' is not defined

In [ ]:
random_vector  = np.random.rand(30)

mean_value = np.mean(random_vector)

print(f" the mean value is: {mean_value}")

 the mean value is: 0.3490334614761961


In [ ]:

rows, cols = np.shape
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1
array[:, 0] = 1
array[-1, :] = 1
array[:, -1] = 1

print(array)

TypeError: cannot unpack non-iterable numpy._ArrayFunctionDispatcher object

In [ ]:
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Get the dimensions of the existing array
rows, cols = existing_array.shape

# Create a new array with expanded dimensions
new_array = np.zeros((rows + 2, cols + 2), dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[1:-1, 1:-1] = existing_array


# printing Array with Border 
print(new_array)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [8]:
!pydoc numpy.add


Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the

In [ ]:
import numpy as np
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
matrix = np.zeros((5, 5), dtype=int)

# Set the values just below the diagonal
matrix[0, 0] = 0
matrix[1, 1] = 1
matrix[2, 2] = 2
matrix[3, 3] = 3
matrix[4, 4] = 4

print(matrix)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [ ]:
matrix = np.zeros((8, 8), dtype=int)


matrix[::2, ::2] = 1  # Fill even rows and even columns with 1
matrix[1::2, 1::2] = 1  # Fill odd rows and odd columns with 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
shape = (6, 7, 8)

# Calculate the linear index of the 100th element
linear_index = 100

# Convert the linear index into a multi-dimensional index
index_3d = np.unravel_index(linear_index, shape)

print("Index (x, y, z) of the 100th element:", index_3d)

Index (x, y, z) of the 100th element: (1, 5, 4)


In [ ]:
matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print(normalized_matrix)

[[0.67628009 0.01614318 0.43752626 0.08461065 0.04511782]
 [0.48442149 0.14531149 0.19996912 0.58979295 0.08601029]
 [0.15316525 0.41102401 0.2587716  0.57288323 0.88311838]
 [0.         0.76724326 0.78308293 1.         0.15350792]
 [0.91126794 0.27147397 0.76964161 0.66104767 0.6168589 ]]


In [ ]:
color_dtype = np.dtype([('R', np.uint8),  # Red component 
                        ('G', np.uint8),  # Green component
                        ('B', np.uint8),  # Blue component 
                        ('A', np.uint8)]) # Alpha component

# Example color in RGBA format
color = np.array((255, 0, 0, 255), dtype=color_dtype)

print("Custom dtype for RGBA color:", color)

Custom dtype for RGBA color: (255, 0, 0, 255)


In [ ]:
matrix1 = np.random.rand(5, 3) # 5x3 matrix

# Create a 3x2 matrix
matrix2 = np.random.rand(3, 2)

# Multiply the matrices
result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1 (5x3):")
print(matrix1)
print("\nMatrix 2 (3x2):")
print(matrix2)
print("\nResulting Matrix (5x2) after multiplication:")
print(result_matrix)

Matrix 1 (5x3):
[[0.79253005 0.46525934 0.4295726 ]
 [0.42245151 0.68427649 0.04299704]
 [0.44353349 0.01230451 0.7651621 ]
 [0.94110922 0.23525709 0.86692417]
 [0.40776862 0.77792212 0.22607256]]

Matrix 2 (3x2):
[[0.20347412 0.11384894]
 [0.41664295 0.46756319]
 [0.11642467 0.06512134]]

Resulting Matrix (5x2) after multiplication:
[[0.40511923 0.33574119]
 [0.37606284 0.37083818]
 [0.18445792 0.10607733]
 [0.39044094 0.2735971 ]
 [0.43340655 0.42487392]]


In [ ]:
elements = np.random.rand(9)
print(elements)

print(elements[3:9])

[0.50304129 0.59197164 0.46907875 0.01980891 0.96388552 0.63697632
 0.85650192 0.09790191 0.40778123]
[0.01980891 0.96388552 0.63697632 0.85650192 0.09790191 0.40778123]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
z = np.arange(3)

print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j * z)
print(z/1/1)
print(z<z>z) # this is not legal

[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\uer\AppData\Local\Temp\ipykernel_112\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\uer\AppData\Local\Temp\ipykernel_112\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\uer\AppData\Local\Temp\ipykernel_112\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) # the expression is false

C:\Users\uer\AppData\Local\Temp\ipykernel_112\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-09
Today: 2024-02-10
Tomorrow: 2024-02-11


In [ ]:
from datetime import datetime, timedelta

# Define the start date as July 1st, 2016
start_date = datetime(2016, 7, 1)

# Define the end date as July 31st, 2016
end_date = datetime(2016, 7, 31)

# Generate all the dates corresponding to the month of July 2016
dates_in_july_2016 = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

# Print the list of dates
for date in dates_in_july_2016:
    print(date)

2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


In [ ]:
import numpy as np 
# Create arrays A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute (-A/2) in place
np.negative(A, out=A)
np.divide(A, 2, out=A)

# Compute (A+B) in place
np.add(A, B, out=A)

# Multiply (A+B) by (-A/2) in place
np.multiply(A, -1, out=A)
np.divide(A, 2, out=A)

print(A)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [ ]:
# Create a random array of positive numbers
random_array = np.random.rand(5) * 10

# Method 1: Using astype method
integer_part1 = random_array.astype(int)

print("Method 1:", integer_part1)

Method 1: [6 3 1 6 2]


In [ ]:
# Create a row vector ranging from 0 to 4
row_values = np.arange(5)

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
# Define a generator function to generate 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Use the generator function to build an array
array = np.fromiter(generate_integers(), dtype=int)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12, endpoint=False)[1:-1]

print(vector)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


In [ ]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random vector:")
print(random_vector)
print("\nSorted vector:")
print(sorted_vector)

Random vector:
[0.00728743 0.43981452 0.24869177 0.96335469 0.97218852 0.44991449
 0.74378963 0.11343678 0.6594597  0.37423637]

Sorted vector:
[0.00728743 0.11343678 0.24869177 0.37423637 0.43981452 0.44991449
 0.6594597  0.74378963 0.96335469 0.97218852]


In [ ]:
# Example small array
small_array = [1, 2, 3, 4, 5]

# Sum the elements using the built-in sum function
sum_result = sum(small_array)

print("Sum using built-in sum function:", sum_result)


Sum using built-in sum function: 15


In [ ]:
# Generate two random arrays A and B
A = np.random.rand(5) 
B = np.random.rand(5)

# Check if arrays A and B are equal
equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are arrays A and B equal?", equal)

Array A: [0.08620533 0.38069335 0.97482353 0.06215577 0.06527273]
Array B: [0.71993131 0.61970325 0.00435912 0.28608159 0.66868531]
Are arrays A and B equal? False


In [ ]:
# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable (read-only)
my_array.flags.writeable = False

# Try to modify the array (this will raise an error)
try:
    my_array[0] = 10
except ValueError as e:
    print("Error:", e)

# Print the array
print("Immutable Array:", my_array)

Error: assignment destination is read-only
Immutable Array: [1 2 3 4 5]


In [ ]:
cartesian_coordinates = np.random.rand(10, 2)

# Split the Cartesian coordinates into x and y components
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert Cartesian coordinates to polar coordinates
r = np.hypot(x, y)  # radius (distance from origin)
theta = np.arctan2(y, x)  # angle (angle in radians from the positive x-axis)

# Combine radius and angle to get polar coordinates
polar_coordinates = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)


Cartesian Coordinates:
[[0.81043693 0.64101961]
 [0.27600094 0.01145061]
 [0.77167339 0.64958028]
 [0.53332198 0.29638209]
 [0.85129083 0.42593689]
 [0.70446038 0.58094839]
 [0.37813909 0.69742168]
 [0.04502173 0.38829531]
 [0.64822793 0.81602135]
 [0.88600026 0.18879739]]

Polar Coordinates:
[[1.03330255 0.66920167]
 [0.27623836 0.04146381]
 [1.00867951 0.69970333]
 [0.61014316 0.50723045]
 [0.95190247 0.46392148]
 [0.91310759 0.68960455]
 [0.79333862 1.07396458]
 [0.39089667 1.45536462]
 [1.04215656 0.89949396]
 [0.90589234 0.2099494 ]]


In [ ]:
import numpy as np

# Define the grid size
grid_size = 10  # Adjust this value as needed

# Create arrays of x and y coordinates covering the [0,1]x[0,1] area
x_coords = np.linspace(0, 1, grid_size)
y_coords = np.linspace(0, 1, grid_size)

# Create a meshgrid of x and y coordinates
x_mesh, y_mesh = np.meshgrid(x_coords, y_coords)

# Create a structured array with x and y coordinates
structured_array = np.empty((grid_size, grid_size), dtype=[('x', float), ('y', float)])
structured_array['x'] = x_mesh
structured_array['y'] = y_mesh

print(structured_array)


[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [ ]:
print("Integer Types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__:>6}: Min={info.min}, Max={info.max}")

# Print minimum and maximum representable values for unsigned integer types
print("\nUnsigned Integer Types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__:>6}: Min={info.min}, Max={info.max}")

# Print minimum and maximum representable values for floating point types
print("\nFloating Point Types:")
for dtype in [np.float16, np.float32, np.float64, np.float128]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__:>9}: Min={info.min}, Max={info.max}")

Integer Types:
  int8: Min=-128, Max=127
 int16: Min=-32768, Max=32767
 int32: Min=-2147483648, Max=2147483647
 int64: Min=-9223372036854775808, Max=9223372036854775807

Unsigned Integer Types:
 uint8: Min=0, Max=255
uint16: Min=0, Max=65535
uint32: Min=0, Max=4294967295
uint64: Min=0, Max=18446744073709551615

Floating Point Types:


AttributeError: module 'numpy' has no attribute 'float128'

In [ ]:
arr = np.arange(12).reshape(3, 4)

# Print entire array
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 6

# Find the index of the closest value to the scalar in the vector
closest_index = np.argmin(np.abs(vector - scalar))

# Get the closest value
closest_value = vector[closest_index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest Value:", closest_value)

Vector: [1 3 5 7 9]
Scalar: 6
Closest Value: 5


In [ ]:
# Define the dtype for the structured array
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]

# Create a structured array with the specified dtype
structured_array = np.array([((1.0, 2.0), (255, 0, 0)),  # Example data point 1
                             ((3.0, 4.0), (0, 255, 0)),  # Example data point 2
                             ((5.0, 6.0), (0, 0, 255))],  # Example data point 3
                            dtype=dtype)

print(structured_array)

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


In [ ]:
# Generate random vector of shape (100, 2) representing coordinates
coordinates = np.random.rand(100, 2)

# Calculate point-by-point distances
distances = np.linalg.norm(coordinates[:, np.newaxis] - coordinates, axis=-1)

print(distances)

[[0.         0.93724071 0.94565282 ... 0.19048854 0.42050844 0.38868374]
 [0.93724071 0.         0.25848065 ... 0.7549224  0.69314605 0.74206467]
 [0.94565282 0.25848065 0.         ... 0.75518257 0.8129549  0.8549832 ]
 ...
 [0.19048854 0.7549224  0.75518257 ... 0.         0.35887789 0.34984252]
 [0.42050844 0.69314605 0.8129549  ... 0.35887789 0.         0.05145728]
 [0.38868374 0.74206467 0.8549832  ... 0.34984252 0.05145728 0.        ]]
